### ISSUE TITLE
3.6节的磁盘读取代码，错误位置未找到。

### ISSUE THREAD

**Issue by da1234cao** [yifengyou/os-elephant#1]
我代码中调用磁盘读取代码之后，便无法向下执行。
但是没有找到**磁盘读取代码的错误之处**

os-elephant/doc/《操作系统真象还原》勘误.md ，该文件也没有给出错误的地方。

请问，群号是什么，可以加入吗？

另外：感觉，纠错的排版格式，有待修改。

**Comment by ghost** [comment]
不知道有没有解决，可以尝试调试一下。
